Add random serial number to each OpenSSL generated certificate
omjadas/hudsucker pull request #24
Opened 2022-03-03 20:45 UTC by glossiness

Firefox seems to block certificates if they use an already seen serial number.

This generates a random serial number for each certificate generated by OpenSSL.

2022-03-03 22:25 UTC, omjadas commented
Thanks for the fix. I am wondering though if it would be better to simply assign an incrementing serial number to each generated certificate. That would ensure that each certificate in a session would definitely have a unique serial number, whereas with a random number it is possible (though probably very unlikely) that a serial number may be reused.

2022-03-04 09:47 UTC, glossiness commented
Thanks for your reply.

Aside from other problems, the per session incremental serial number wouldn't work, for example, if the proxy is restarted while the browser is running.

The CA Browser Forum requires the following : "CAs SHALL generate non‐sequential Certificate serial numbers greater than zero (0) containing at least 64 bits of output from a CSPRNG" (section 7.1 of https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.8.1.pdf).

In this PR proposed implementation, there is 128 bit entropy. There should be no practical concern for duplicates. Maybe this can give you an idea why : https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions .

2022-03-04 10:09 UTC, omjadas requested changes

2022-03-04 10:09 UTC, omjadas commented on src/certificate_authority/openssl_authority.rs
> +        rand_serial_number[0] &= 0b0111_111; // MSB should be 0 to be considered positive
```suggestion
        rand_serial_number[0] &= 0b0111_1111; // MSB should be 0 to be considered positive
```

2022-03-05 05:39 UTC, glossiness commented on src/certificate_authority/openssl_authority.rs
> +        rand_serial_number[0] &= 0b0111_111; // MSB should be 0 to be considered positive
Good catch !

2022-03-05 05:43 UTC, omjadas commented
Thanks again for the fix. I will most likely do a release with this later today or tomorrow.

2022-03-05 05:46 UTC, merged

2022-03-05 23:09 UTC, omjadas commented
Released as part of https://github.com/omjadas/hudsucker/releases/tag/v0.14.1

2022-03-06 09:03 UTC, glossiness commented
Thank you very much